### ISSUE TITLE
Merging rash into hashie 2?

### ISSUE THREAD

**Issue by jch** [tcocca/rash#7]
Thanks for building rash! I've used jt in the past to build API clients.

I've been helping out with hashie recently and pushed out hashie 2.0. Would you be interested in adding rash to the hashie gem?

**Comment by tcocca** [comment]
Hi, glad you like Rash.  Building API clients was exactly the reason I started rash.

Here was the initial discussion about adding Rash to Hashie:  https://github.com/intridea/hashie/issues/7

If we want to re-visit that I'd be happy to merge, but initially they didn't really seem to be too into it.

~ Tom

**Comment by jch** [comment]
Ah, I missed this. I'll read over it and see whether any of the arguments
have since changed

On Saturday, February 16, 2013, Tom Cocca wrote:

> Hi, glad you like Rash. Building API clients was exactly the reason I
> started rash.
> 
> Here was the initial discussion about adding Rash to Hashie:
> intridea/hashie#7 https://github.com/intridea/hashie/issues/7
> 
> If we want to re-visit that I'd be happy to merge, but initially they
> didn't really seem to be too into it.
> 
> ~ Tom
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/tcocca/rash/issues/7#issuecomment-13679636.

## 

-Jerry
@whatcodecraves http://twitter.com/whatcodecraves
github http://github.com/jch

**Comment by tcocca** [comment]
Closing as I definitely don't think this is going to happen now that hashie has its own rash: https://github.com/intridea/hashie/blob/master/lib/hashie/rash.rb  (see our issue #9 ).
